CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT NOT NULL, pass TEXT NOT NULL, balance INTEGER DEFAULT 0, loc INTEGER DEFAULT 0, health INTEGER DEFAULT 100);

CREATE TABLE npc (id INTEGER PRIMARY KEY AUTOINCREMENT, triggers TEXT, answer TEXT);

CREATE TABLE items (id INTEGER PRIMARY KEY AUTOINCREMENT, loc INTEGER, owner INTEGER);

CREATE TABLE inventory (id INTEGER PRIMARY KEY AUTOINCREMENT, ownby INTEGER, item_counter INTEGER, item_id INTEGER);

CREATE TABLE items_list(id INTEGER PRIMARY KEY AUTOINCREMENT, item_id INTEGER, title TEXT, descr TEXT);

CREATE TABLE items_attr(id INTEGER PRIMARY KEY AUTOINCREMENT, item_id INTEGER, title TEXT, val INTEGER);