CREATE TABLE users (id SERIAL PRIMARY KEY, username CHAR(30) NOT NULL, pass CHAR(60) NOT NULL, balance INTEGER DEFAULT 0, loc INTEGER DEFAULT 0, health INTEGER DEFAULT 100);

CREATE TABLE npc (id SERIAL PRIMARY KEY, name CHAR(30), triggers TEXT, answer TEXT);

CREATE TABLE stacks (id SERIAL PRIMARY KEY, loc INTEGER, owner INTEGER, quantity INTEGER, itemname CHAR(120), descr TEXT);

CREATE TABLE inventory (id SERIAL PRIMARY KEY, ownby INTEGER, stack_id INTEGER);