CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT NOT NULL, pass TEXT NOT NULL, balance INTEGER DEFAULT 0, loc INTEGER DEFAULT 0);

CREATE TABLE npc (id INTEGER PRIMARY KEY AUTOINCREMENT, triggers TEXT, answer TEXT);

CREATE TABLE items (id INTEGER PRIMARY KEY AUTOINCREMENT, loc INTEGER, owner INTEGER);

CREATE TABLE inventory (id INTEGER PRIMARY KEY AUTOINCREMENT, ownby INTEGER, item_counter INTEGER, item_type INTEGER);

